# Generated by Django 5.2 on 2025-07-04 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original filename', max_length=255)),
                ('sheet_name', models.CharField(blank=True, default='', help_text='Excel sheet name if applicable', max_length=100)),
                ('use_ai', models.BooleanField(default=True, help_text='Whether AI insights were generated')),
                ('results', models.JSONField(help_text='Complete analysis results in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analysis_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analysis_re_created_2bdd23_idx'), models.Index(fields=['file_name'], name='analysis_re_file_na_eb17b2_idx')],
            },
        ),
    ]
