# Generated by Django 5.2 on 2025-07-08 00:42

import apps.analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='access_token',
            field=models.CharField(default=apps.analysis.models.generate_access_token, help_text='Access token for secure retrieval', max_length=64),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['access_token'], name='analysis_re_access__29e036_idx'),
        ),
    ]
