# Generated by Django 5.2 on 2025-07-14 21:54

import apps.analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='access_token',
            field=models.CharField(default=apps.analysis.models.generate_access_token, help_text='Access token for secure retrieval', max_length=64, unique=True),
        ),
    ]
