# Generated by Django 5.2 on 2025-07-22 02:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_email_verified',
            new_name='registration_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Email Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='pending_verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login_method',
            field=models.CharField(blank=True, choices=[('email', 'Email/Magic Link'), ('google', 'Google'), ('github', 'GitHub')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(choices=[('email', 'Email/Magic Link'), ('google', 'Google'), ('github', 'GitHub')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='social_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_confirmation_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Confirmation Token',
                'verbose_name_plural': 'Email Confirmation Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
